.travis.yml
Makefile
README.md
requirements.txt
src/validate_mhc_allele_restriction.py

Given Jason's SQL schema:
```
Name                                      Null?    Type
----------------------------------------- -------- ----------------------------
MHC_ALLELE_RESTRICTION_ID                 NOT NULL NUMBER
DISPLAYED_RESTRICTION                              VARCHAR2(85 CHAR)
SYNONYMS                                           VARCHAR2(200)
INCLUDES                                           VARCHAR2(85 CHAR)
RESTRICTION_LEVEL                                  VARCHAR2(35 CHAR)
ORGANISM                                           VARCHAR2(150 CHAR)
ORGANISM_NCBI_TAX_ID                               NUMBER
CLASS                                              VARCHAR2(35 CHAR)
HAPLOTYPE                                          VARCHAR2(10 CHAR)
LOCUS …
```

Add SQL schema validation for mhc_allele_restriction table

---

iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/molecule.tsv

This update adds two new terms:
* `MRO:0035799` - Mamu-E*02:11 chain	
* `MRO:0035800` - Mamu-E*02:11 protein complex
This also renames two cow terms:
| ID | Old Label | New Label |
| --- | --- | --- |
| MRO:0000939 | BoLA-DQA\*012:01:01/DQB*10051 | BoLA-DQA\*012:01:01/DQB*10:05 |
| MRO:0000958 | BoLA-DRB3*4501 protein complex | BoLA-DRB3*045:01 protein complex |

2020-11-12 Update

---

Makefile
iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/external.tsv
ontology/genetic-locus.tsv
ontology/molecule.tsv
src/clean.py
src/update_seqs.py

This PR adds two new species:
* giant panda (NCBITaxon:9646)
* grass carp (NCBITaxon:7959)
It adds 18 terms related to these new species:
ID | Label
-- | --
MRO:0036986 | giant panda MHC class I locus
MRO:0036987 | giant panda MHC class II locus
MRO:0036988 | grass carp MHC class I locus
MRO:0036989 | grass carp MHC class II locus
MRO:0036990 | Aime-128 locus
MRO:0036991 | Ctid-UAA locus
MRO:0036992 | Aime-128 chain
MRO:0036993 | Ctid-UAA chain
MRO:0037012 | Aime-128 protein complex
MRO:0037013 | Ctid-UAA protein complex
MRO:0037032 | giant panda MHC class I chain
MRO:0037033 | giant panda MHC class II chain
MRO:0037034 | grass carp MHC class I chain
MRO:0037035 | grass carp MHC class II chain
MRO:0037036 | giant panda MHC class I protein complex
MRO:0037037 | giant panda MHC class II …

2020-11-24 update

---

iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/genetic-locus.tsv
ontology/molecule.tsv

This PR includes 8 new terms:
ID | Label
--- | ---
MRO:0037040 | Mafa-A1 locus
MRO:0037041 | crab-eating macaque MHC class I locus
MRO:0037042 | Mafa-A1 chain
MRO:0037043 | Mafa-A1*063:01 chain
MRO:0037044 | crab-eating macaque MHC class I chain
MRO:0037045 | Mafa-A1*063:01 protein complex
MRO:0037046 | Mafa-A1 protein complex
MRO:0037047 | crab-eating macaque MHC class I protein complex

2020-12-02 update

---

iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/core.tsv
ontology/external.tsv
ontology/genetic-locus.tsv
ontology/molecule.tsv
src/scripts/validate_templates.py

"Ctid-UAA protein complex" renamed to "Ctid-UAA b2m-1-II protein complex" (MRO:0037013)
Addition of 6 new terms:
ID | Label
--- | ---
MRO:0037048 | grass carp Beta-2-microglobulin locus
MRO:0037049 | Beta-2-microglobulin locus
MRO:0037050 | grass carp Beta-2-microglobulin-1-II chain
MRO:0037051 | grass carp Beta-2-microglobulin-2 chain
MRO:0037052 | grass carp Beta-2-microglobulin chain
MRO:0037053 | Ctid-UAA b2m-2 protein complex
I also had to update the template validation script to handle the new b2m terms.

2020-12-15 update

---

Makefile
ontology/external.tsv
ontology/import.txt
requirements.txt
src/scripts/prefixes.sql

This uses an unreleased version of `ontodev-gizmos`. It's the most recent on the master branch: https://github.com/ontodev/gizmos
Instead of importing all terms from all imports, this divides the imports into different subsets and extracts only what we need from each import. It also adds an IAO import to resolve the OBI issue where many IAO terms have multiple labels, definitions, etc. The OBI import text file is a little different because it includes GO & PR terms.
I then added a second extract step with ROBOT after everything is merged to make sure we don't get the *full* hierarchy of terms, since `gizmos.extract` goes all the way to the top.
Note that I updated "protein complex" to "protein-containing complex" here, because it fails otherwise (this old term no longer exists in OBI). …

First pass at fixing imports

---

src/names.rq
src/parents.rq
src/search.rq

Update `ALLELE_FINDER_*.csv` queries to replace `obo:GO_0043234` (obsolete) with `obo:GO_0032991` (protein-containing complex)

Update GO ID in queries

---

iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/molecule.tsv

removed extra digits from:
BoLA-4\*024:01:01:01
BoLA-DQA\*012:01:01
BoLA-DQA\*022:02:01
updated nomenclature for
DQB\*10051
BoLA-DRB3\*4501
added synonym for
BoLA-3\*00101
added expression for
HLA-C\*03:284 chain
removed extra space from
HLA-DPA1\*02:01/ DPB1\*13:01

2021-01-14 Updates

---

iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/molecule.tsv

Updates from @rvita:
1) added new duck term Anpl-UAA*SD
2) updated dog (DLA) nomenclature & chain sequences
2) updated horse (Eqca) nomenclature & chain sequences (note 1 left unchanged on purpose)
3) updated gorilla (Gogo) nomenclature & chain sequences
The Travis builds are always going to fail since https://build.obolibrary.io/ is down - we can update to use a released ROBOT JAR once v1.8.0 is released, since we're using some unreleased features for TDB. Running `make test` locally passes.

2021-01-22 updates

---

index.tsv
ontology/chain.tsv
ontology/molecule.tsv

Four new terms (two of which are obsolete):
ID | Label
--- | ---
MRO:0045939 | Patr-B*01:02 chain
MRO:0045940 | Patr-B*01:02 protein complex	
MRO:0045941 | obsolete SLA-6*01:02 chain
MRO:0045942 | obsolete SLA-6*01:02 protein complex
Other changes:
* Removed duplicate "HLA-DQA1*01:04 chain"
* Updated "Mamu-A4*01:02 chain"

2021-03-29 update

---

ontology/chain.tsv
ontology/molecule.tsv

Two obsolete terms were created recently, but they did not have the "obsolete" appended to their labels in `chain` and `molecule`. These terms should not be in these files, anyway, as obsolete terms should not have logic.
I've confirmed that `make clean test` passes.

Remove logic from obsolete terms

---

src/scripts/validate_templates.py

Currently, "error"-level messages just print a warning but do not cause the `make` process to fail. This fixes that issue.

Fail on error-level messages in validate_template

---

iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/external.tsv
ontology/genetic-locus.tsv
ontology/molecule.tsv

Updates:
- New species with MHC class I & class II protein complexes:
- rainbow trout
- atlantic salmon
- bighorn sheep
- goat
- Renamed "sheep" to "domestic sheep" to prevent confusion with "bighorn sheep"
- Added expression evidence to chains:
- HLA-B*35:460Q
- HLA-C*04:61N
- HLA-DQA1*01:07Q
- Moved "RLA-A protein complex" and "RLA-A*01 protein complex" under "MHC class I protein complex" to match existing pattern for other terms like these

2021-05-03 update

---

iedb/iedb.tsv
index.tsv
ontology/haplotype-molecule.tsv
ontology/haplotype.tsv

Three new terms:
ID | Label
--- | ---
MRO:0045954 | BF2 haplotype
MRO:0045955 | chicken MHC class II protein complex with BF2 haplotype
MRO:0045956 | chicken MHC class II protein complex with B2 haplotype
And "HLA-DQA1\*02:01/DQB1\*06:02 protein complex" added to the IEDB sheet.

2021-06-23 update

---

Makefile
src/scripts/export_molecule.py

This new `molecule_export.tsv` will be packaged in the zip we include with each release. It contains the following:
* MRO ID
* Label
* IEDB Label
* Synonyms (separated by pipe)
* Parent
* In Taxon
* In Taxon ID
I was originally going to use `gizmos.export` for this, but with the "In Taxon" restriction, this took almost 10 minutes, so it just seemed better to use the existing TSVs - which is pretty much instant. That said, I kept the indexes because we'll probably need them anyway.
Resolves #99

Add custom export for molecule table

---

Makefile
index.tsv
ontology/chain.tsv
ontology/external.tsv
ontology/genetic-locus.tsv
ontology/molecule.tsv
src/scripts/replace_labels.py
src/scripts/validation/validate_templates.py

This PR contains 294 new MRO terms. They are the "MHC class I" and "MHC class II" locus, chain, and protein complex terms for 49 new NCBI taxon in `external.tsv`.
6 of these taxon terms contain a single quote, which breaks `robot template`. As a workaround, I've included a new script to replace usages with their IDs. Originally I was planning to use `sed` and just replace the NCBITaxon terms, but the MRO terms are also referenced in places so we needed to be a little smarter about it (e.g., "Azara's night monkey MHC class I locus"). This will allow Randi to add more terms with single quotes in the future without it being an issue.

2021-07-06 Update

---

ontology/chain.tsv
src/queries/verify/verify-proteins.rq

This should fail until we resolve an issue where some RT1 chains are asserted children of 'protein'. I'll make that fix in this same branch as soon as I confirm with Randi that it's OK to do so.

Verify no direct children of protein

---

iedb/iedb.tsv
index.tsv
ontology/chain.tsv
ontology/genetic-locus.tsv
ontology/molecule.tsv

Updates:
* One term added to IEDB tab (HLA-DPA1\*01:03/DPB1\*10:01 protein complex)
* Fixed labels for two terms to include "/"
And three new terms:
ID | Label
--- | ---
MRO:0046251 | human Beta-2-microglobulin chain
MRO:0046252 | H2-Db/human Beta-2-microglobulin protein complex
MRO:0046253 | human Beta-2-microglobulin locus

2021-07-22 update

---

iedb/iedb.tsv
index.tsv
ontology/mutant-molecule.tsv

Add three new terms to `mutant-molecule`:
ID | Label
--- | ---
MRO:0046254 | mutant pig MHC class I protein complex
MRO:0046255 | SLA-1*13:01 F99Y mutant protein complex
MRO:0046256 | SLA-1*04:01 R156A mutant protein complex

2021-07-27 update

---

src/scripts/synonyms.py

From @rvita:
> for all paired human protein complexes (2 chains)
we need an additional automated synonym for chain 2 with the "HLA" part added.
For ex, for
HLA-DQA1\*03:01/DQB1\*03:02
needed synonym is
HLA-DQB1\*03:02

Add new synonyms for paired human protein complexes

---

iedb/iedb.tsv

adds one row to iedb tab:
HLA-DPA1*02:01/DPB1*16:01 protein complex
this term already existed in` index.tsv `and `molecule.tsv`, but was not yet in `iedb.tsv`.

2021-12-15_update

---

Makefile
src/queries/mhc_allele_restriction.rq
src/scripts/add_chain_accessions.py
src/scripts/validation/validate_mhc_allele_restriction.py

Get the chain accessions from chain-sequence for IMGT/HLA terms only. These are added as two new columns in the `mhc_allele_restriction` TSV for IEDB - `chain_i_accession` and `chain_ii_accession`.

Add script to add chain accessions for IEDB terms

---

Makefile
src/queries/mhc_allele_restriction.rq
src/scripts/add_chain_accessions.py
src/scripts/validation/validate_mhc_allele_restriction.py

Add `chain_i_mro_id` and `chain_ii_mro_id` (corresponding to the chain accessions) to the table for IEDB. Jason has already checked the files and loaded them to IEDB, so the columns and the data are good to go.

Add MRO IDs for chains to IEDB table
