MRO_UNSTABLE.owl, MRO_UNSTABLE_IEDB.owl, Makefile, mro-core.csv
- add 'protein complte' to mro-core.csv
- update Makefile to depend on mro-core.csv
- update OWL files
=> Add IEDB label for 'protein complex'

Makefile, ontology/rejected.tsv
This is in the `ontology` folder, but it doesn't get built into any of the release products. I'll send the updated XLSX to @rvita once this is approved.
=> Add rejected terms table

Makefile
Resolves #59 
This depends on https://github.com/ontodev/robot/pull/792 - just to make things a little cleaner. I guess if we don't want to add that feature to ROBOT I can update the Makefile here instead 🙂
=> Use TDB when querying

iedb/iedb.tsv, index.tsv, ontology/chain.tsv, ontology/molecule.tsv
From @rvita:
> updates to existing terminology to match new IPD nomenclature for mamu terms
=> 2021-01-13 update

Makefile
Also remove `mro.owl` when running `make clean`
=> Update ROBOT JAR

.gitignore, Makefile, requirements.txt, src/scripts/cogs.sh, src/scripts/validate_templates.py
We'll need to provide `credentials.json` in the DROID branch for now to handle the Google credentials for COGS. I updated Gizmos as well to handle some bugs.
=> Update DROID workflow

requirements.txt, src/scripts/tree.sh
* Add the search functionality to the MRO tree browser
* Add missing `urlp` requirement
* Change `psycopg2` to `psycopg2-binary`
=> Small fixes for DROID

iedb/iedb.tsv
This PR just adds one term to the IEDB tab.
=> 2021-07-12 update

.gitignore, Makefile, src/scripts/update_seqs.py
Added new task `refresh-hla-seqs` that only overwrites existing HLA sequences, then ran this task to update.
=> Update HLA sequences

index.tsv, ontology/chain.tsv, ontology/genetic-locus.tsv, src/scripts/sort.py
- Atbe-B*01 chain
- BoLA-3*084:01N chain
- BoLA-3*086:01N chain
- BoLA-3*098:01N chain
- Atbe-B*01 protein complex
- BoLA-3*084:01N protein complex
- BoLA-3*086:01N protein complex
- BoLA-3*098:01N protein complex
I also changed the sort script to output the same number of columns for each row, and updated some existing tables to match.
=> Add more Atbe and BoLA complexes

.gitignore, iedb/iedb.tsv
adds one new term to `molecule`:
HLA-DQA1 * 03:01/DQB1 * 06:04 protein complex
=> 2021-11-24 update

ontology/chain.tsv, src/scripts/validation/validate_templates.py
This also removes existing duplicates in the `chain` and `molecule` templates.
=> Add check for duplicates

Makefile, index.tsv, ontology/chain.tsv, ontology/core.tsv, ontology/external.tsv, ontology/genetic-locus.tsv, src/scripts/validation/validate_templates.py
Resolves #129 
* Replaced 'genetic locus' (`REO:0000079`) with gene (`SO:0000704`)
* Updated all '... locus' labels to be '... gene'
* Obsoleted 'genetic entity' and moved haplotype, haplotype_block, and gene to top level
=> Replace 'genetic locus' with SO gene

Makefile, iedb/iedb.tsv, index.tsv
added 2 new terms to the iedb tab:
HLA-DPA1*01:03/DPB1*16:01 protein complex
HLA-DRA*01:01/DRB1*04:02 protein complex
and created 1 new molecule using existing chains:
HLA-DRA*01:01/DRB1*04:02 protein complex
=> 2022-01-18_update

Makefile, iedb/iedb.tsv, src/scripts/sort_iedb.py
This PR makes two additions to `iedb.tsv`, both already existed on the index tab:
HLA-DPA1*01:03/DPB1*15:01 protein complex
HLA-DQA1*01:01/DQB1*06:03 protein complex
=> 2022 02 10 update

iedb/iedb.tsv, index.tsv, ontology/chain.tsv, ontology/evidence.tsv
This PR:
1. makes changes to existing terms, for:
HLA-B*07:44 chain and protein complex
HLA-C*03:23 chain and protein complex
HLA-C*03:284 chain and protein complex
HLA-C*04:61 chain and protein complex
HLA-A*01:159 chain and protein complex
HLA-A*01:281 chain and protein complex
HLA-A*02:437 chain and protein complex
HLA-A*02:581 chain and protein complex
HLA-A*02:728 chain and protein complex
HLA-A*02:795 chain and protein complex
HLA-A*24:329 chain and protein complex
HLA-A*24:378 chain and protein complex
HLA-B*18:106 chain and protein complex
HLA-B*27:185 chain and protein complex
HLA-B*35:460 chain and protein complex
HLA-B*41:56 chain and protein complex
HLA-C*04:338 chain and protein complex
HLA-C*07:226 chain and protein complex
HLA-C*07:432 chain and protein complex
HLA-C*07:713 …
=> 2022-06-13-update

iedb/iedb.tsv, index.tsv, ontology/chain.tsv, ontology/external.tsv, ontology/genetic-locus.tsv
This PR adds two new terms to `iedb.tsv`, `genetic-locus.tsv`, `chain.tsv`, and `molecule.tsv`
1. Chinese tree shrew MHC class I 
2. Chinese tree shrew MHC class II 
It also adds 1 term to `external.tsv`
1. Chinese tree shrew
=> 2022-08-03-update

iedb/iedb.tsv
This PR adds pre-existing term to the iedb tab
MRO:0002118 Mamu-E protein complex
=> 2022-10-07-update

iedb/iedb.tsv, index.tsv, ontology/chain.tsv, ontology/external.tsv, ontology/genetic-locus.tsv
This PR adds ‘Tasmanian devil’ to` external.tsv`.
It adds ‘Tasmanian devil MHC class I protein complex’ and ‘Tasmanian devil MHC class II protein complex’ to `molecule.tsv`.
It adds ‘Tasmanian devil MHC class I chain’ and ‘Tasmanian devil MHC class II chain’ to `chain.tsv`. 
It adds ‘Tasmanian devil MHC class I gene’ and ‘Tasmanian devil MHC class II gene’ to `genetic-locus.tsv`.
And it adds ‘Tasmanian devil MHC class I protein complex’ and ‘Tasmanian devil MHC class II protein complex’ to `iedb.tsv`.
=> 2022-11-28-update

.github/workflows/mro-test.yml, .github/workflows/refresh-hla.yml, iedb/iedb.tsv
This PR adds HLA-DQA1*01:04/DQB1*02:01 protein complex, which already existed, to the `iedb.tsv`.
=> 2023-02-08-update

iedb/iedb.tsv
This PR adds 2 existing complexes to the iedb tab:
HLA-DQA1*03:02/DQB1*02:01 protein complex
HLA-DQA1*03:02/DQB1*02:02 protein complex
=> 2023-02-19-update
